"use client";

import { Copy, Download, RefreshCw } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

import { BoardFrame } from "@/components/board/BoardFrame";
import { Callout } from "@/components/callout";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogTitle,
} from "@/components/ui/dialog";
import { TYPE_LABEL } from "@/features/boards/history";
import type { BoardDetail } from "@/features/boards/queries";
import { isTemplateKey } from "@/features/templates/registry";

type BoardDetailDialogProps = {
  board: BoardDetail | null; // open while set
  onClose: () => void;
  onRegenerate: (board: BoardDetail) => void;
};

// history-board.html: a dialog on desktop, a bottom sheet under 760px
// (the Dialog component's phone layout). Everything shown comes from the
// snapshot; today's rates only add the gold "Now X".
export function BoardDetailDialog({
  board,
  onClose,
  onRegenerate,
}: BoardDetailDialogProps) {
  // Keep showing the last board while the dialog animates closed.
  const [shown, setShown] = useState(board);
  if (board && board !== shown) setShown(board);

  return (
    <Dialog open={board !== null} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="max-w-[min(900px,calc(100vw-32px))]">
        {shown && (
          <div className="overflow-auto p-6 pb-[calc(24px+env(safe-area-inset-bottom))]">
            <div className="mb-[18px] pr-10">
              <DialogTitle className="text-[20px] font-[750]">
                {TYPE_LABEL[shown.type]}
              </DialogTitle>
              <DialogDescription className="text-text-secondary">
                {shown.when}
              </DialogDescription>
            </div>

            <div className="grid gap-7 shell:grid-cols-[300px_minmax(0,1fr)]">
              <div className="mx-auto w-full max-w-[220px] shell:max-w-none">
                {isTemplateKey(shown.templateKey) ? (
                  <BoardFrame
                    templateKey={shown.templateKey}
                    snapshot={shown.snapshot}
                    label={`${TYPE_LABEL[shown.type]} from ${shown.snapshot.content.timeLabel}`}
                    className="shadow-[0_18px_40px_rgb(31_11_63/0.25)]"
                  />
                ) : (
                  <div className="aspect-[9/16] rounded-control bg-bg-subtle" />
                )}
              </div>

              <div className="min-w-0">
                <dl className="mb-5 grid grid-cols-[auto_1fr] gap-x-[18px] gap-y-1.5 text-[14px]">
                  <dt className="text-text-muted">Generated by</dt>
                  <dd className="font-semibold">{shown.generatedBy}</dd>
                  <dt className="text-text-muted">Template</dt>
                  <dd className="font-semibold">
                    {shown.templateName}, version {shown.templateVersion}
                  </dd>
                  <dt className="text-text-muted">Image</dt>
                  <dd className="font-semibold">
                    1080 × 1920 PNG
                    {shown.imageCount > 1 && `, ${shown.imageCount} images`}
                  </dd>
                </dl>

                <h3 className="text-[13.5px] font-semibold">
                  Rates on this board
                </h3>
                <ul className="mt-2 mb-4 overflow-hidden rounded-xl border border-border-default">
                  {shown.rates.map((rate) => (
                    <li
                      key={rate.key}
                      className="flex justify-between gap-3 border-b border-border-subtle px-3.5 py-[9px] text-[14px] last:border-b-0"
                    >
                      <b>{rate.label}</b>
                      <span className="text-right tabular-nums">
                        {rate.value}
                        {rate.now && (
                          <span className="block text-[12.5px] font-semibold text-accent-gold-text">
                            {rate.now}
                          </span>
                        )}
                        {rate.gone && (
                          <span className="block text-[12.5px] text-text-muted">
                            No longer listed
                          </span>
                        )}
                      </span>
                    </li>
                  ))}
                </ul>

                <Callout className="mb-[18px]">
                  This board is a saved snapshot. It shows the rates from{" "}
                  {shown.snapshot.content.timeLabel}, even where current rates
                  have changed.
                </Callout>

                <div className="flex flex-wrap gap-2.5">
                  <Button asChild disabled={!shown.latestImageId}>
                    <a href={`/api/boards/${shown.id}/download`} download>
                      <Download aria-hidden="true" strokeWidth={1.9} />
                      Download PNG
                    </a>
                  </Button>
                  <Button variant="outline" onClick={() => onRegenerate(shown)}>
                    <RefreshCw aria-hidden="true" strokeWidth={1.9} />
                    Regenerate
                  </Button>
                  <Button asChild variant="ghost">
                    <Link href={`/admin/generator?from=${shown.id}`}>
                      <Copy aria-hidden="true" strokeWidth={1.9} />
                      Use these rates again
                    </Link>
                  </Button>
                </div>
              </div>
            </div>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}
