// Board fonts: the same Archivo WOFF files for Satori (server) and for
// BoardFrame (browser), under the same two family names, so the PNG and
// the preview use identical glyphs. Run after upgrading @fontsource/archivo:
//   node scripts/copy-fonts.mjs
//
// - assets/fonts/  read by Satori (src/lib/render/fonts.ts). WOFF, not WOFF2.
// - public/fonts/  served to the browser.
// - src/components/board/board-fonts.css  generated @font-face rules.
//
// "Archivo Board" is the latin file; "Archivo Board latin-ext" the
// latin-ext file (₦ lives only there). Satori only falls back per glyph
// between different family names, so the browser uses the same two names.
// Unique names: next/font already declares a browser family "Archivo".
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const pkg = join(root, "node_modules/@fontsource/archivo");
const from = join(pkg, "files");
const targets = [join(root, "assets/fonts"), join(root, "public/fonts")];

const WEIGHTS = [400, 500, 600, 700, 800, 900];
const SUBSETS = [
  { file: "latin", family: "Archivo Board" },
  { file: "latin-ext", family: "Archivo Board latin-ext" },
];

// The unicode ranges fontsource publishes for each subset.
function unicodeRange(subset) {
  const css = readFileSync(join(pkg, "400.css"), "utf8");
  const block = css.split(`/* archivo-${subset}-400-normal */`)[1] ?? "";
  const match = /unicode-range:\s*([^;]+);/.exec(block);
  if (!match) throw new Error(`No unicode-range for ${subset}`);
  return match[1].trim();
}

for (const dir of targets) mkdirSync(dir, { recursive: true });

const faces = [];
for (const subset of SUBSETS) {
  const range = unicodeRange(subset.file);
  for (const weight of WEIGHTS) {
    const file = `archivo-${subset.file}-${weight}-normal.woff`;
    const source = join(from, file);
    if (!existsSync(source)) throw new Error(`Missing ${source}`);
    for (const dir of targets) copyFileSync(source, join(dir, file));
    faces.push(
      `@font-face {\n  font-family: "${subset.family}";\n  font-style: normal;\n  font-weight: ${weight};\n  font-display: block;\n  src: url("/fonts/${file}") format("woff");\n  unicode-range: ${range};\n}`,
    );
    console.log(`copied ${file}`);
  }
}

writeFileSync(
  join(root, "src/components/board/board-fonts.css"),
  `/* Generated by scripts/copy-fonts.mjs. Do not edit by hand.\n * The board fonts for BoardFrame: the same WOFF files and family names\n * Satori uses (src/lib/render/fonts.ts), so the preview matches the PNG. */\n\n${faces.join("\n\n")}\n`,
);
console.log("wrote src/components/board/board-fonts.css");
